//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellPhoneShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int MaSo { get; set; }
        public string MaGioHang { get; set; }
        public int MaSP { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime NgayTao { get; set; }
    }
}
